language: node_js

node_js:
   - "0.8"
   - "0.10"
   - "0.12"
   - "iojs-v1"
   - "iojs-v2"
   - "iojs-v3"
   - "4.2"
   - "5.5"
   - "6.12"
   - "8.9"
   - "9.11"
   - "10.10"
   - "11.1"
   - "node"

addons:
  apt:
    packages:
      - rabbitmq-server

before_install:
   - node --version | (grep  -v 'v5' && npm install -g npm@2) || true

before_script: "./bin/ci/before_build"

sudo: required
